# CI 
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

include: 
  - project: shared-group/templates
    ref: 'v2.0.1'
    file: hiddenJobs/Renovate.yml
  - project: shared-group/templates
    ref: 'v2.0.1'
    file: Jobs/Build-JDK17.yml
  - project: shared-group/templates
    ref: 'v2.0.1'
    file: Jobs/Deploy-JDK17.yml
  - project: shared-group/templates
    ref: 'v2.0.1'
    file: Jobs/SonarQube.yml

variables:
  RELEASE_TYPE:
    value: "none"
    options:
    - "none"
    - "major"
    - "minor"
    - "patch"
    description: "Do you want to create a new release?"

stages:
  - release
  - build
  - scan
  - deploy
  - renovate

init-new-release:
  stage: release
  image: gitlab.idst.ibaintern.de/shared-group/buildimages/build-jdk17:latest
  rules:
    - if: $RELEASE_TYPE != "none"
  script: 
    - |
      git remote set-url origin https://$SVC_USER_USERNAME:$SVC_USER_PASSWORD@gitlab.idst.ibaintern.de/oiam-keycloak-group/keycloak-extension-filestore.git
      git config --global user.email "IT-Systemhaus.K13-Team-OPDT@arbeitsagentur.de"
      git config --global user.name "CI"
      git checkout $CI_COMMIT_REF_NAME
      ./release.sh $RELEASE_TYPE

build:app:
  artifacts:
    paths:
      - "target/surefire-reports/*.xml"
    reports:
      junit: "target/surefire-reports/*.xml"
  except:
    - tags

sonar:java:
  variables:
    SONAR_QUALITYGATE_WAIT: "false" # TODO: Turn on as soon as QG is reached
  except:
    - tags

deploy:app:
  only:
    - tags

renovate-run:
  stage: renovate
  extends: .renovate
  variables:
    RENOVATE_AUTODISCOVER_FILTER: oiam-keycloak-group/keycloak-app
    SKIP_SCHEDULES: "true"
    LOG_LEVEL: debug
    RENOVATE_DRY_RUN: "false"

